development:
  adapter: mysql2
  database: mysql-rails-five-one-four_dev
  username: root
  password:
  pool: 5

test:
  adapter: mysql2
  database: mysql-rails-five-one-four_test
  username: root
  password:
  pool: 5
